---
title: "Week 8: Object-oriented programming"
summary: "Learn object-oriented programming concepts in R with a focus on S3 design and methods."
prepare: "Read the S3 chapter and skim the comparison resources if you need a broader OO refresher."
resource_label: "Advanced R S3"
resource_url: "https://adv-r.hadley.nz/s3.html"
focus:
  - "S3 classes and methods"
  - "Object-oriented programming concepts in R"
  - "How S3 compares with other OO systems"
  - "Useful references for S4, R6, and S7"
---

```{r}
week <- 8
source(here::here("course_info.R"))
```

```{r}
#| output: asis
show_week_overview(week)
```

## Main reference

* [13 *Advanced R*](https://adv-r.hadley.nz/s3.html)

## What you will learn this week

Overview of object-oriented programming in R, focusing on S3.

```{r}
#| output: asis
show_slides(week)
show_assignments(week)
```

## Online resources

* [A simple guide to S3 methods](https://www.njtierney.com/post/2016/11/06/simple-s3-post/)
* [S4: a short guide for the perplexed](https://stuartlee.org/2019/07/09/s4-short-guide/)
* [Comparing S3 and S4 on an example](https://faculty.washington.edu/kenrice/sisg-adv/sisg17-pack-03.pdf)
* [S4](https://kasperdanielhansen.github.io/genbioconductor/html/R_S4.html)
* [R6](https://r6.r-lib.org/)
* [S7](https://rconsortium.github.io/S7/)
